version: "3.5"
services:
  task-service:
    container_name: task-service
    image: task-service:latest
    command: npm run dev:watch # Hot reload
    ports:
      - "3000:3000"
    build:
      context: .
      target: DEV
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
