version: '3.5'
services:
  task-service:
    container_name: task-service
    image: task-service:latest
    environment:
      - LOG_FILE_DIR=logs
      - ALLOWED_ORIGIN=http://localhost:3003
      - PORT=3001
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    ports:
      - '3001:3001'
    build: .
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:latest
