version: "3.5"
services:
  task-service:
    image: task-service:latest
    ports:
      - "3001:3001"
    build: .
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - LOG_FILE_DIR=logs
      - PORT=3001
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:latest
